import '../styles/globals.css';
import '../styles/navbarStyles.css';
import '../styles/custom-inputs.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'animate.css';
import "aos/dist/aos.css";
import AppLayout from '../components/AppLayout/AppLayout'
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <AppLayout>
      <Head>
        <title>פאר אנפון תעשיות בע&quot;מ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Component {...pageProps} />
    </AppLayout>
  )
}

export default MyApp
