import ImagesGallery from '../components/ImagesGallery/ImagesGallery';

const images = [
    { src: "/images/enter-doors/A-301.jpg" },
    { src: "/images/enter-doors/A-302.jpg", strechType: "vStrech" },
    { src: "/images/enter-doors/A-303.jpg", strechType: "bigStrech" },
    { src: "/images/enter-doors/A-304.jpg" },
    { src: "/images/enter-doors/A-305.jpg" },
    { src: "/images/enter-doors/A-306.jpg", strechType: "hStrech" },
    { src: "/images/enter-doors/A-307.jpg", strechType: "bigStrech" },
    { src: "/images/enter-doors/A-308.jpg" },
    { src: "/images/enter-doors/A-309.jpg", strechType: "hStrech" },
    { src: "/images/enter-doors/A-310.jpg" },
    { src: "/images/enter-doors/A-311.jpg" },
    { src: "/images/enter-doors/A-312.jpg" },
    { src: "/images/enter-doors/A-313.jpg", strechType: "bigStrech" },
    { src: "/images/enter-doors/A-314.jpg" },
    { src: "/images/enter-doors/A-315.jpg", strechType: "bigStrech" },
    { src: "/images/enter-doors/A-316.jpg" },
    { src: "/images/enter-doors/A-317.jpg", strechType: "hStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_1.jpeg", strechType: "" },
    { src: "/images/intercom/R-453.jpg", strechType: "vStrech" },
    { src: "/images/intercom/R-454.jpg", strechType: "vStrech" },
    { src: "/images/intercom/R-455.jpg", strechType: "vStrech" },
    { src: "/images/intercom/R-456.jpg", strechType: "vStrech" },
    { src: "/images/intercom/R-456b.jpg", strechType: "vStrech" },
    { src: "/images/intercom/R-457.jpg", strechType: "vStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_2.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_4.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_5.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_6.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_7.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_8.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_9.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_10.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_3.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_11.jpeg", strechType: "vStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_12.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_13.jpeg", strechType: "hStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_14.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_15.jpeg", strechType: "hStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_16.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_17.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_18.jpeg", strechType: "vStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_19.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_28.jpeg", strechType: "hStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_20.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_21.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_22.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_26.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_27.jpeg", strechType: "hStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_29.jpeg", strechType: "hStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_30.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_31.jpeg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-8.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-1.jpg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-2.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-4.jpeg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-3.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_23.jpeg", strechType: "" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_24.jpeg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-6.jpeg", strechType: "vStrech" },
    { src: "/images/automatic-doors/doubleLeaf-door/double_leaf_25.jpeg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-9.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-5.jpeg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-7.jpg", strechType: "" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-10.jpeg", strechType: "bigStrech" },
    { src: "/images/automatic-doors/singleLeaf-door/singleleaf-11.jpeg", strechType: "" },
    { src: "/images/mailboxes/deposit-cellphones/Y-1.jpg", strechType: "" },
    { src: "/images/mailboxes/deposit-cellphones/Y-2.jpg", strechType: "" },
    { src: "/images/mailboxes/deposit-cellphones/Y-3.jpg", strechType: "" },
    { src: "/images/mailboxes/deposit-cellphones/Y-5.jpeg", strechType: "" },
    { src: "/images/mailboxes/deposit-cellphones/Y-6.jpeg", strechType: "" },
    { src: "/images/mailboxes/mailbox-rooms/R-001.jpeg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-435.jpeg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-426.jpeg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-428.jpg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-428b.jpg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-434.jpeg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-431.jpeg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-432.jpg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-433.jpg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-433.jpg", strechType: "" },
    { src: "/images/mailboxes/organizations/T-439.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-301.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-302.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-303.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-304.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-305.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-306.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-307.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-308.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-309.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-310.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-311.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-312.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-313.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-314.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-315.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-316.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-317.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-318.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-319.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-319b.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-320.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-321.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-322.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-323.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-324.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-325.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-326.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-327.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-328.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-329.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-330.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-331.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-332.jpg", strechType: "" },
    { src: "/images/mailboxes/private-houses/P-333.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-401.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-408.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-407.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-405.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-425.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-404.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-432.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-409.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-406.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-412.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-413.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-411.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-410.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-445.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-437.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-402.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-442.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-439.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-403.jpg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-427.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-436.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-440.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-431.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-443.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-448.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-441.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-430.jpeg", strechType: "" },
    { src: "/images/mailboxes/shared-houses/T-444.jpeg", strechType: "" },
];

export default function Gallery() {
    return (
        <div className="mt-5 mb-5">
            <div className="push-from-navbar"></div>
            <div className="mb-5 page-title">
                <h1 className="text-shine">גלריית תמונות</h1>
            </div>
            <div className="mb-5 separator"></div>

            <ImagesGallery images={images} altLabel={"תמונת גלרייה פאר אנפון תעשיות בע\"מ"} />
        </div>
    );
}